# Generated by Django 4.1 on 2022-08-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crystal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('colors', models.CharField(max_length=100)),
                ('properties', models.TextField(max_length=250)),
            ],
        ),
    ]
