# Generated by Django 4.1 on 2022-08-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cleansing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cleansing',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='crystal',
            old_name='type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='cleansing',
            name='cleanse',
            field=models.CharField(choices=[('S', 'Selenite'), ('W', 'Water'), ('I', 'Incense'), ('M', 'Moonlight')], default='S', max_length=1, verbose_name='Method of Cleansing Used'),
        ),
        migrations.AlterField(
            model_name='cleansing',
            name='date',
            field=models.DateField(verbose_name='Date of Last Cleanse'),
        ),
        migrations.AddField(
            model_name='crystal',
            name='cuts',
            field=models.ManyToManyField(to='main_app.cut'),
        ),
    ]
